spring:
  profiles:
    default: local
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true